### ISSUE TITLE
Incompatilibity with gnuradio 3.8.2.0 (latest on Debian)

### ISSUE THREAD

**Issue by cojocar** [argilo/secplus#18]
Hi,

I'm getting the following error on Debian:
```
$ python3  ./secplus_rx.py 
Warning: failed to XInitThreads()
Traceback (most recent call last):
  File "/mnt/a/projects/sdr/secplus/./secplus_rx.py", line 295, in <module>
    main()
  File "/mnt/a/projects/sdr/secplus/./secplus_rx.py", line 273, in main
    tb = top_block_cls()
  File "/mnt/a/projects/sdr/secplus/./secplus_rx.py", line 50, in __init__
    gr.top_block.__init__(self, "Secplus Rx", catch_exceptions=True)
TypeError: __init__() got an unexpected keyword argument 'catch_exceptions'
```
Is this an incompatibility with my GNURadio?

I'm testing this verion:
```
$ gnuradio-config-info --version
3.8.2.0```

**Comment by argilo** [comment]
If you want to use GNU Radio 3.8, you'll have to check out the older maint-3.8 branch: `git checkout maint-3.8`. It doesn't have as many features, but it should run.
